version: "3"

services:

  backend:
    build:
      context: ./server
      dockerfile: dockerfile
    image: chat-app-react-nodejs-master:server
    container_name: server
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    env_file: ./server/.env
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - mongo-data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017

  frontend:
    
    build:
      context: ./public
      dockerfile: dockerfile
    image: chat-app-react-nodejs-master:public
    container_name: public
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./public:/usr/app
      - /usr/app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

networks:
  react-express:
  express-mongo:
volumes:
  mongo-data:
    driver: local
